### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by evhumphrey** [voorheesmatthew/Matsana#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

* Awesome job on the proposal! There's a few notes under comment headings in this checklist.

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

- No need for an `img_url` in your schema. You can use [Active Storage](https://github.com/appacademy/curriculum/tree/master/full-stack-project/resources/ActiveStorageDemo) for setting this up.

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

* While `snake_case` on the backend, you'll want the json returned to have `camelCase` keys. This is a pretty cool resource on this: [APIs supporting snake_case and camelCase with Rails](https://crypt.codemancers.com/posts/2016-03-25-api-transformations-in-rails/)

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

* `GET /api/teams/:user_id` - all teams for a user: This one will work, but it could be a nested route if needed: `GET /api/users/:user_id/teams`
* `GET /api/projects/:team_id` - all projects for a team && `GET /api/projects/:id` - returns a project won't work together as they are the same route (if we go to `/api/projects/4`, is 4 the `:user_id` or the `:team_id`?). I suggest putting all projects for a team at an endpoint like: `GET /api/teams/:team_id/projects`
* `GET /api/tasks/:user_id/:team_id` will work, but it will look kinda funky if you use it (`/api/tasks/1/4`). I suggest having a nested route: `GET /api/users/:user_id/tasks` and pass an additional query string that can be used to filter `/api/users/3/tasks?team_id=2`. You could fully nest it like `/api/users/:user_id/teams/:team_id/tasks` as another option.
* You may have some superfluous routes, for example, I don't know if you'll ever need to get 1 task at a time (you'll probably get them from getting your projects); but maybe there is a scenario for that?

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by voorheesmatthew** [comment]
Hi @evhumphrey,

Thank you for all the great feedback!

## I took care of the following items:

### Wiki Home Page, Schema, and Sample State:
- Added a link/placeholder for a link to the live page
- Removed the note about `img_url` in the schema
- Changed all snake_case to camelCase

### Backend Routes:
- Nested teams index
- Nested projects index
- Fully Nested tasks index

## I have a few remaining questions:

### Backend Routes:
- I will need to access a specific task to add a description or any other attribute like attachments, tags, etc. (see attached) but maybe I'm still haven't fully wrapped my head around the use of frontend vs. backend routes. 

<img width="1267" alt="screen shot 2018-10-08 at 5 14 08 pm" src="https://user-images.githubusercontent.com/40614234/46639876-a35be980-cb1d-11e8-9802-0b2769c390ff.png">


That being said...

- [ ] Should I leave my "`GET /api/tasks/:id` - returns a task"?

### Frontend Routes:
- It looks like everything got marked off as complete here, with no comments. So I just wanted to double check; Basically, my strategy was to list any form or fetching of info I thought I might need under (from what I could tell from actual asana) sections of the app. I plan to stick to the design doc plans, but want to be extra sure of my strategy. Backtracking no good!

- [ ] Everything is good with frontend routes?

Thanks again!!

**Comment by evhumphrey** [comment]
Great reply, so easy to read!

You probably won't need your `GET /api/tasks/:id` backend route as you'll probably fetch all the tasks when fetching a project. You should already have the info you need in your redux store to render the task detail ui. 

Regarding frontend routes, they look good to me.

**Comment by voorheesmatthew** [comment]
Cool. Done!
Now to get started.
