### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by voorheesmatthew** [voorheesmatthew/Matsana#3]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by voorheesmatthew** [comment]
@evhumphrey, I've pushed a "functioning" app to heroku.

**Comment by evhumphrey** [comment]
💯
